### ISSUE TITLE
Add Kobo's analyzer export feature for multi-selects

### ISSUE THREAD

**Issue by batkinson** [cims-bioko/briefcase#1]
As a data analyst, I want briefcase to export multi-selects as boolean grids similar to KoboToolkit's analyzer export tool, so that I can analyze multi-select questions directly in a statistics tool (Stata, SPSS, etc) without a lot of pre-processing.

![image](https://user-images.githubusercontent.com/478997/41312117-484b4476-6e54-11e8-8fc4-6600a2bf79a5.png)

**Comment by lognaturel** [comment]
This is something there's been interest in on the ODK side as well! CC @yanokwa @ggalmazor

@batkinson, nice to see you back on the Internet, you've been missed. Very glad @aurdipas noticed you were back here.

**Comment by ggalmazor** [comment]
Hi everyone! :)

It seems like this would create an extra column per multi-select choice. Did I catch that right?

Some thoughts/questions:
- Is this intended to happen by default or are we expecting this to be configurable by the user? (maybe with a toggle that enables the creation of those columns)
- It would be good to encode headers the same way. I guess we can start by looking how Kobo does it.

**Comment by batkinson** [comment]
Thank you. It's nice to be back. Only took coming to the States for an
intense week-long work trip, which is almost up.

So, this is something I will be looking to do quickly (next two weeks),
which is why I added the issue to the cims-bioko fork. However, the result
is something very much intended to be contributed back to the project (if
possible). We have campaigns coming up and our analysis folks were
complaining about having to munge these questions manually in their stats
tool.

Good questions Guillermo, I was thinking it would be an export option, but
wasn't sure what would be natural since I haven't had an opportunity to
dive into it. My first plan was to take a peek at how they do it too.

**Comment by yanokwa** [comment]
I'd love to see this added to trunk and it seels like it should be an option for users to select.

Ona and [odkmeta](https://github.com/PovertyAction/odkmeta) also do this. Might be good to take a quick look at all them and adopt the format if it is consistent.

**Comment by batkinson** [comment]
I took a look at how kobo does it here https://github.com/kobotoolbox/kobocat/blob/ca01bf72302e32983128231d22240b085207b7bf/onadata/libs/utils/export_tools.py#L322. It appears that it's fairly simple. Generate a column for each choice, named "question/choice" (as pictured above). For each row, split the original value. For each choice, set the value to true if it was in the set of selections. False if it wasn't.

**Comment by ggalmazor** [comment]
Sounds good!

I did a little research to see if there are any major blockers for this new feature. Here are my findings:

Briefcase currently uses a `FieldMapper` functional interface to map a tuple - composed among others of the `Element` to map and the form's `Model` - into a list of output columns - modeled as a `Pair<String, String>` (column name, row value).

The `Model` class is a wrapper of a `TreeElement`  that corresponds initially to the root of the form's model and then it's navigated (get the child model of a field, group, etc.), but they can't be used to get to their corresponding `IFormElement`s. 

Instead, we would need to get a map of field FQNs and their control `DataType`s and pass it to the `Model` to be able to ask about each field's control's data type. This block sort-of takes care of that:

```java
Map<String, DataType> controlDataTypes = briefcaseFormDefinition.formDefn.rootJavaRosaFormDef.getChildren()
    .stream()
    .flatMap(FormDefinition::flatten) // This is something like Model.flatten
    .filter(e -> e instanceof QuestionDef)
    .map(e -> (QuestionDef) e)
    .collect(toMap(
        e -> e.getBind().getReference().toString(),
        e -> DataType.from(e.getControlType())
    ));
```
_Missing in this expression: generation of FQNs for the map's keys_

Once we have that, we could *decorate* the existing `FieldMapper`s with a post-processing step that would generate those extra columns if a model's control type is a `DataType.CHOICE_LIST`.

**Comment by batkinson** [comment]
After taking a swipe at this, it seems the export design is overwrought. What starts in ExportPanel as ExportToCsv.export turns into a fight to define an abstraction that *might possbily* work for other export formats, but fails given this simple extension. What I was hoping to see was something with a flatter design. Ultimately, an export can be thought of as a function.

Input:
  * form design (with full details of question, choices, etc.)
  * collection of form instances
  * exporter configuration/options

Output:
  * A collection of files or network traffic that represent the data/media collected in the configured format

The problem with the current design is that it is a pipeline that immediately defines the output format (CSV) and next eliminates the form design details (the form definition) before allowing you to define the export operation. This means that you have to do acrobatics to define an operation that would be natural with the full details in scope.

**Comment by ggalmazor** [comment]
Hi, @batkinson! 

I'm sorry you don't like the current design. I don't like it either and I agree with you on that it has a lot of room for improvement yet. I never considered it to be finished, though. It has to evolve, like any other part of Briefcase and I was hoping to be able to discuss it with you since you're now being more active and I regard you as someone that really could make a difference.

Let me put together a PR with the approach I'd take and we can continue the conversation there if you want.

**Comment by batkinson** [comment]
Oh, please don't take this as anything personal. I'm just making note of the design issue for my own benefit. It took me a while to identify what I felt was wrong with it to begin with. I actually have a working export (see 8d7564efab328b17edea1bd03ad05ab9d5d65091), minus the pieces to make it optional. You'll definitely have better idea of the code, since I am seeing your name a lot on git blame for the files I'm working in, so don't hesitate to go anouther route.

Edit: @ggalmazor - sorry, just re-read this and I don't like how it came off. My mentioning git blame was a bit of a non-sequitur, I know it's *not your design*. I was just noticing that you've been working in the same code a lot.

**Comment by batkinson** [comment]
After attempting to make the export optional, I am identifying additional flaws with the current design. The export is split between headers and actual data lines. These are implicitly coupled, rather than explicitly through something like `Model` as you would expect. This leads to fragility and duplication in code to generate these, since they are not intrinsically linked. This is visible by the need for case-coding the number of headers based on the type for GPS, and similarly the mapper for converting GPS questions to match the headers generated. Essentially, the abstraction is not sufficient for capturing the whole reality yet.

**Comment by ggalmazor** [comment]
Hi, @batkinson!

It's great to have somebody else's feedback on this. I think it would be easier for you if we could have a conversation about the design strategy and motives for the current state of Briefcase's design, though.

I've updated [my branch](https://github.com/ggalmazor/briefcase/tree/spike_multichoice_exports) with a basic working version of this (working for statically defined select items only).

So far, the biggest issues I'm having come from my lack of experience juggling JavaRosa. Now I'm trying to support dynamic itemsets but I'm hitting some JR walls ([maybe you could help me with that](https://github.com/ggalmazor/briefcase/blob/spike_multichoice_exports/src/org/opendatakit/briefcase/export/FormDefinition.java#L118)).

I've taken a quick look at [your commit](https://github.com/cims-bioko/briefcase/commit/8d7564efab328b17edea1bd03ad05ab9d5d65091) and I have a question regarding data types and control types. My current understanding of how ODK's XForm implementation works is that a field's can be of `INTEGER` data type, for example, and have a user-facing of  `SELECT_MULTI` control type bound to it. How would that work on your implementation?

**Comment by ggalmazor** [comment]
By the way, do you need to support dynamic itemsets as a first pass? 

Also, my branch supports optionally exploding the choice list fields. Does it do everything you need within an acceptable design?

**Comment by lognaturel** [comment]
@batkinson I wanted to make sure you saw that this functionality will be in the next Briefcase release. It's just on the command line for now and will eventually be added to the UI. See https://github.com/opendatakit/briefcase/pull/577 and hopefully it can be useful to you.

**Comment by batkinson** [comment]
I looked at briefcase proper, it doesn't appear that we can use yet since it's only command-line driven. Also, always splitting the dynamic select-multiples doesn't make sense for our purposes since are often quite large. Looks like we will have to continue to run a fork for a bit. This was pushed as the analyze-export branch.
